
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Name }}
  name: {{ .Name }}
  namespace: default
spec:
  clusterIP: {{ .ClusterIP }}
  ports:
  - port: {{ .Port }}
    protocol: TCP
    targetPort: {{ .Port }}
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: {{ .Name }}
  name: {{ .Name }}
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: {{ .Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Name }}
    spec:
      containers:
      - image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always